name: Deploy React App

on:
  push:
    branches:
      - main  # または your-deploy-branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # ✅ ここで .env を作成
      - name: Set up .env file
        run: |
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
          echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> .env

      - name: Create firebase.js
        run: |
          echo "import { initializeApp } from 'firebase/app';" > src/firebase.js
          echo "import { getStorage } from 'firebase/storage';" >> src/firebase.js
          echo "const firebaseConfig = {" >> src/firebase.js
          echo "  apiKey: '${{ secrets.REACT_APP_FIREBASE_API_KEY }}'," >> src/firebase.js
          echo "  authDomain: '${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}'," >> src/firebase.js
          echo "  projectId: '${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}'," >> src/firebase.js
          echo "  storageBucket: '${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}'," >> src/firebase.js
          echo "  messagingSenderId: '${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}'," >> src/firebase.js
          echo "  appId: '${{ secrets.REACT_APP_FIREBASE_APP_ID }}'" >> src/firebase.js
          echo "};" >> src/firebase.js
          echo "const app = initializeApp(firebaseConfig);" >> src/firebase.js
          echo "export const storage = getStorage(app);" >> src/firebase.js

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      # 例: GitHub Pages にデプロイ（使ってるサービスに応じて変更）
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
